[project]
name = "example-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nba-api>=1.7",
    "pandas>=2.2.3",
    "polars-lts-cpu>=1.29.0",
    "pyarrow>=19.0.1",
    "scikit-learn>=1.6.1",
]

[tool.ruff]
unfixable=['F401']
