[project]
name = "example-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nba-api>=1.7",
    "pandas>=2.2.3",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
unfixable = ["F401", "F841"]

[dependency-groups]
dev = [
    "ruff>=0.9.3",
]
